#!/usr/bin/env python3
"""Universal STRATA-to-UWFA integration adapter.

No extracted selected-bit, polar-level, or base-frequency file is an input to
this module.  They are regenerated by running the frozen universal STRATA SC
decoder on the literal inherited metadata and arithmetic payload.  The new
decoder replaces only the arithmetic ``decode(freq1)`` operation.

NumPy, CuPy, the frozen independent STRATA auditor, and the STRATA format
module are injected from an externally authenticated source snapshot.  This
module deliberately performs no repository-relative import.
"""

from __future__ import annotations

import hashlib
import math
import struct
from dataclasses import dataclass
from typing import Any, Callable, Sequence


IMMUTABLE_MAGIC = b"STUWFA2\x00"
IMMUTABLE_VERSION = 2
IMMUTABLE_HEADER_BYTES = 128
IMMUTABLE_BLOCK_RECORD_BYTES = 8


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _stream_digest(bits: bytes, levels: bytes, base_u16le: bytes) -> str:
    digest = hashlib.sha256()
    for item in (bits, levels, base_u16le):
        digest.update(struct.pack("<Q", len(item)))
        digest.update(item)
    return digest.hexdigest()


def owner_mask_for_block(strata_common: Any, ordinal: int) -> int:
    owners = strata_common.block_owner_experts(ordinal)
    mask = 0
    for owner in owners:
        mask |= 1 << int(owner)
    if mask <= 0:
        raise ValueError("empty STRATA owner set")
    return mask


@dataclass(frozen=True)
class BaselineBlock:
    ordinal: int
    logn: int
    owner_mask: int
    profile_q: int
    decoder_scale: float
    decoder_scale_bits: bytes
    logical_bits: int
    payload: bytes
    sc_seed_u32: int
    rht_seed_u64: int


class UWFAArithmeticDecoder:
    """Arithmetic-like causal object consumed by ``decode_sc_level``."""

    def __init__(
        self,
        common: Any,
        base_decoder: Any,
        candidate: Any,
        frequencies: Sequence[int],
    ) -> None:
        if len(frequencies) != common.model_frequency_count(candidate):
            raise ValueError("UWFA frequency geometry")
        self.common = common
        self.base_decoder = base_decoder
        self.candidate = candidate
        self.frequencies = frequencies
        self.state = 0
        self.position = 0
        self.level = 0
        self.decoded_bits: list[int] = []
        self.original_frequencies: list[int] = []
        self.uwfa_frequencies: list[int] = []
        self.levels: list[int] = []

    def set_level(self, level_zero_based: int) -> None:
        level = int(level_zero_based)
        if not 0 <= level < self.common.LEVELS:
            raise ValueError("polar level outside universal context")
        self.level = level

    def decode(self, original_freq1: int) -> int:
        within = self.position % self.candidate.reset_length
        if within == 0:
            self.state = 0
        context = self.common.public_context(self.level, int(original_freq1), within)
        uwfa_freq1 = int(self.frequencies[self.state * self.common.CONTEXTS + context])
        bit = int(self.base_decoder.decode(uwfa_freq1))
        if bit not in (0, 1):
            raise ValueError("nonbinary arithmetic decoder result")
        self.decoded_bits.append(bit)
        self.original_frequencies.append(int(original_freq1))
        self.uwfa_frequencies.append(uwfa_freq1)
        self.levels.append(self.level)
        self.state = self.common.transition(self.candidate, self.state, bit, context, within)
        self.position += 1
        return bit


class RecordingOriginalDecoder:
    """Pass-through baseline decoder that records decoder-visible contexts."""

    def __init__(self, decoder: Any) -> None:
        self.decoder = decoder
        self.level = 0
        self.decoded_bits: list[int] = []
        self.original_frequencies: list[int] = []
        self.levels: list[int] = []

    def set_level(self, level_zero_based: int) -> None:
        self.level = int(level_zero_based)

    def decode(self, original_freq1: int) -> int:
        bit = int(self.decoder.decode(int(original_freq1)))
        self.decoded_bits.append(bit)
        self.original_frequencies.append(int(original_freq1))
        self.levels.append(self.level)
        return bit


def parse_current_artifact(
    raw: bytes,
    *,
    strata_common: Any,
    frozen_auditor: Any,
) -> dict[str, Any]:
    """Parse, semantically validate, and byte-slice the held baseline artifact."""
    if len(raw) != int(strata_common.PHYSICAL_BYTES):
        raise ValueError("baseline physical byte count")
    header_end = int(strata_common.HEADER_BYTES)
    route_end = header_end + int(strata_common.ROUTE_BYTES)
    labels_end = route_end + int(strata_common.LABEL_BYTES)
    directory_end = labels_end + int(strata_common.DIRECTORY_BYTES)
    header = raw[:header_end]
    route = raw[header_end:route_end]
    labels_packed = raw[route_end:labels_end]
    directory_raw = raw[labels_end:directory_end]
    strata_common.validate_header(header, route, labels_packed)
    route_rows = strata_common.parse_route(route)
    labels = strata_common.unpack_labels(labels_packed)
    if len(route_rows) != int(strata_common.MATRICES):
        raise ValueError("route matrix count")
    shape_weight_sum = 0
    for row in route_rows:
        role = str(row["role"])
        shape = (2048, 768) if role == "down" else (768, 2048)
        shape_weight_sum += shape[0] * shape[1]
    if shape_weight_sum != int(strata_common.WEIGHTS):
        raise ValueError("shape-derived weights disagree with artifact")
    profiles = bytearray()
    cursor = directory_end
    blocks: list[BaselineBlock] = []
    for ordinal in range(int(strata_common.BLOCKS)):
        q, scale, logical_bits = struct.unpack_from(
            "<BeI", directory_raw, ordinal * int(strata_common.DIRECTORY_RECORD_BYTES)
        )
        if not math.isfinite(float(scale)) or float(scale) <= 0.0 or logical_bits <= 0:
            raise ValueError("baseline block directory value")
        payload_bytes = (int(logical_bits) + 7) // 8
        end = cursor + payload_bytes
        if end > len(raw):
            raise ValueError("baseline arithmetic payload outside artifact")
        payload = raw[cursor:end]
        if logical_bits & 7 and payload[-1] & ((1 << (8 - (logical_bits & 7))) - 1):
            raise ValueError("baseline arithmetic terminal padding")
        profiles.append(int(q))
        blocks.append(BaselineBlock(
            ordinal=ordinal,
            logn=int(strata_common.BLOCK_LOG2[ordinal]),
            owner_mask=owner_mask_for_block(strata_common, ordinal),
            profile_q=int(q),
            decoder_scale=float(scale),
            decoder_scale_bits=directory_raw[ordinal * 7 + 1:ordinal * 7 + 3],
            logical_bits=int(logical_bits),
            payload=payload,
            sc_seed_u32=0,
            rht_seed_u64=0,
        ))
        cursor = end
    if any(raw[cursor:]):
        raise ValueError("nonzero baseline terminal reservoir")
    seeded: list[BaselineBlock] = []
    for row in blocks:
        sc_seed, rht_seed, _digest = strata_common.derive_seeds(
            header, route, labels_packed, bytes(profiles), row.ordinal
        )
        seeded.append(BaselineBlock(
            ordinal=row.ordinal,
            logn=row.logn,
            owner_mask=row.owner_mask,
            profile_q=row.profile_q,
            decoder_scale=row.decoder_scale,
            decoder_scale_bits=row.decoder_scale_bits,
            logical_bits=row.logical_bits,
            payload=row.payload,
            sc_seed_u32=int(sc_seed),
            rht_seed_u64=int(rht_seed),
        ))
    return {
        "raw_sha256": _sha(raw),
        "raw_bytes": len(raw),
        "weights_from_shapes": shape_weight_sum,
        "header": header,
        "route": route,
        "route_rows": route_rows,
        "labels_packed": labels_packed,
        "labels": labels,
        "profiles": bytes(profiles),
        "blocks": seeded,
        "used_payload_end": cursor,
        "zero_tail_bytes": len(raw) - cursor,
    }


def pack_immutable_metadata(parsed: dict[str, Any], strata_common: Any) -> bytes:
    blocks: list[BaselineBlock] = parsed["blocks"]
    body = bytearray()
    body.extend(parsed["header"])
    body.extend(parsed["route"])
    body.extend(parsed["labels_packed"])
    for row in blocks:
        body.extend(struct.pack("<BBH", row.profile_q, row.logn, row.owner_mask))
        body.extend(row.decoder_scale_bits)
        body.extend(b"\x00\x00")
    header = bytearray(IMMUTABLE_HEADER_BYTES)
    total = IMMUTABLE_HEADER_BYTES + len(body)
    struct.pack_into(
        "<8sHHIIIIQ",
        header,
        0,
        IMMUTABLE_MAGIC,
        IMMUTABLE_VERSION,
        IMMUTABLE_HEADER_BYTES,
        int(strata_common.WEIGHTS),
        int(strata_common.EXPERTS),
        int(strata_common.MATRICES),
        int(strata_common.BLOCKS),
        total,
    )
    header[40:72] = hashlib.sha256(body).digest()
    header[72:104] = hashlib.sha256(parsed["header"] + parsed["route"] + parsed["labels_packed"]).digest()
    header[104:128] = hashlib.sha256(bytes(header[:104])).digest()[:24]
    return bytes(header) + bytes(body)


def unpack_immutable_metadata(payload: bytes, strata_common: Any) -> dict[str, Any]:
    if len(payload) < IMMUTABLE_HEADER_BYTES:
        raise ValueError("short inherited metadata")
    magic, version, header_bytes, weights, experts, matrices, blocks, total = struct.unpack_from(
        "<8sHHIIIIQ", payload, 0
    )
    expected = (
        IMMUTABLE_MAGIC,
        IMMUTABLE_VERSION,
        IMMUTABLE_HEADER_BYTES,
        int(strata_common.WEIGHTS),
        int(strata_common.EXPERTS),
        int(strata_common.MATRICES),
        int(strata_common.BLOCKS),
        len(payload),
    )
    if (magic, version, header_bytes, weights, experts, matrices, blocks, total) != expected:
        raise ValueError("inherited metadata constants")
    if payload[104:128] != hashlib.sha256(payload[:104]).digest()[:24]:
        raise ValueError("inherited metadata header seal")
    body = payload[IMMUTABLE_HEADER_BYTES:]
    if hashlib.sha256(body).digest() != payload[40:72]:
        raise ValueError("inherited metadata body digest")
    cursor = 0
    h_end = cursor + int(strata_common.HEADER_BYTES)
    r_end = h_end + int(strata_common.ROUTE_BYTES)
    l_end = r_end + int(strata_common.LABEL_BYTES)
    header = body[cursor:h_end]
    route = body[h_end:r_end]
    labels_packed = body[r_end:l_end]
    if hashlib.sha256(header + route + labels_packed).digest() != payload[72:104]:
        raise ValueError("inherited semantic metadata digest")
    strata_common.validate_header(header, route, labels_packed)
    labels = strata_common.unpack_labels(labels_packed)
    rows = []
    cursor = l_end
    profiles = bytearray()
    for ordinal in range(int(strata_common.BLOCKS)):
        end = cursor + IMMUTABLE_BLOCK_RECORD_BYTES
        if end > len(body):
            raise ValueError("truncated inherited block record")
        q, logn, owner_mask = struct.unpack_from("<BBH", body, cursor)
        scale_bits = body[cursor + 4:cursor + 6]
        if body[cursor + 6:end] != b"\x00\x00":
            raise ValueError("inherited block reserved bytes")
        scale = struct.unpack("<e", scale_bits)[0]
        if logn != int(strata_common.BLOCK_LOG2[ordinal]) or owner_mask != owner_mask_for_block(strata_common, ordinal):
            raise ValueError("inherited block geometry")
        if not math.isfinite(float(scale)) or float(scale) <= 0.0:
            raise ValueError("inherited scale")
        profiles.append(q)
        rows.append({
            "ordinal": ordinal,
            "profile_q": int(q),
            "logn": int(logn),
            "owner_mask": int(owner_mask),
            "decoder_scale": float(scale),
            "decoder_scale_bits": scale_bits,
        })
        cursor = end
    if cursor != len(body):
        raise ValueError("trailing inherited metadata")
    for row in rows:
        sc_seed, rht_seed, digest = strata_common.derive_seeds(
            header, route, labels_packed, bytes(profiles), row["ordinal"]
        )
        row["sc_seed_u32"] = int(sc_seed)
        row["rht_seed_u64"] = int(rht_seed)
        row["seed_digest_sha256"] = digest
    return {
        "header": header,
        "route": route,
        "route_rows": strata_common.parse_route(route),
        "labels_packed": labels_packed,
        "labels": labels,
        "profiles": bytes(profiles),
        "blocks": rows,
        "weights_from_shapes": sum((2048 * 768) for _row in strata_common.parse_route(route)),
    }


class StrataSCAdapter:
    """Authenticated universal decoder adapter; no checkpoint-specific law."""

    def __init__(self, *, common: Any, np: Any, frozen_auditor: Any, strata_common: Any, device: str = "cupy") -> None:
        if device not in {"numpy", "cupy"}:
            raise ValueError("RHT device")
        self.common = common
        self.np = np
        self.frozen = frozen_auditor
        self.strata = strata_common
        self.device = device

    def _decode_block(
        self,
        *,
        payload: bytes,
        logical_bits: int,
        row: Any,
        arithmetic: Any,
    ) -> dict[str, Any]:
        np = self.np
        n = 1 << int(row.logn if isinstance(row, BaselineBlock) else row["logn"])
        profile_q = int(row.profile_q if isinstance(row, BaselineBlock) else row["profile_q"])
        scale = float(row.decoder_scale if isinstance(row, BaselineBlock) else row["decoder_scale"])
        sc_seed = int(row.sc_seed_u32 if isinstance(row, BaselineBlock) else row["sc_seed_u32"])
        rht_seed = int(row.rht_seed_u64 if isinstance(row, BaselineBlock) else row["rht_seed_u64"])
        profile = self.frozen.profile_parameters(profile_q, 0.25)
        reverse = self.frozen.bit_reverse_indices(n)
        layers = self.frozen.sc_layers(n)
        flags = self.frozen.bec_freeze_flags(n, profile["capacities"], reverse)
        alphabet = 0.25 * np.arange(-31, 33, dtype=np.float64)
        weights = np.exp(-0.5 * (alphabet / float(profile["sigma_reconstruction"])) ** 2)
        previous = np.zeros(n, dtype=np.int16)
        selected_chunks = []
        base_chunks = []
        level_chunks = []
        for level_index, flag in enumerate(flags):
            arithmetic.set_level(level_index)
            level = level_index + 1
            frozen_rng = np.random.default_rng(sc_seed + 1_000_003 * level)
            frozen_external = frozen_rng.integers(0, 2, size=n, dtype=np.uint8)
            prior = self.frozen.leaf_prior_ratios(weights, previous, level)
            x_bit, base_frequencies, selected = self.frozen.decode_sc_level(
                prior, flag, frozen_external, reverse, layers, arithmetic
            )
            previous += (1 << level_index) * x_bit.astype(np.int16)
            selected_chunks.append(selected)
            base_chunks.append(base_frequencies)
            level_chunks.append(np.full(selected.size, level_index, dtype=np.uint8))
        selected_all = np.concatenate(selected_chunks)
        base_all = np.concatenate(base_chunks)
        level_all = np.concatenate(level_chunks)
        transformed = alphabet[previous] * scale
        reconstructed = self.frozen.inverse_signed_rht(transformed, rht_seed, self.device)
        return {
            "selected": selected_all,
            "base": base_all,
            "levels": level_all,
            "indices": previous,
            "reconstructed": reconstructed,
            "logical_bits": int(logical_bits),
            "payload": payload,
        }

    def _full_reconstruction_digest(self, decoded: Sequence[dict[str, Any]], metadata: dict[str, Any]) -> dict[str, Any]:
        np = self.np
        ordinals = self.strata.expected_block_group_ordinals(metadata["labels"])
        post = np.empty((int(self.strata.GROUPS), int(self.strata.GROUP_VALUES)), dtype=np.float64)
        coverage = np.zeros(int(self.strata.GROUPS), dtype=np.uint8)
        for block, group_ordinals in zip(decoded, ordinals, strict=True):
            values = np.asarray(block["reconstructed"], dtype=np.float64).reshape(-1, int(self.strata.GROUP_VALUES))
            post[group_ordinals] = values
            coverage[group_ordinals] += 1
        if not bool(np.all(coverage == 1)):
            raise ValueError("decoded groups do not form exact coverage")
        coefficients = struct.unpack_from("<12f", metadata["header"], 32)
        digest = hashlib.sha256()
        matrix_digests = []
        for expert in range(int(self.strata.EXPERTS)):
            base = expert * int(self.strata.GROUPS_PER_EXPERT)
            gate = np.asarray(post[base:base + 768], dtype="<f8")
            z0 = np.asarray(post[base + 768:base + 1536], dtype=np.float64)
            z1 = np.asarray(post[base + 1536:base + 2304], dtype=np.float64)
            cosine = float(coefficients[2 * expert])
            sine = float(coefficients[2 * expert + 1])
            norm2 = cosine * cosine + sine * sine
            up = np.asarray((cosine * z0 - sine * z1) / norm2, dtype="<f8")
            down = np.asarray((sine * z0 + cosine * z1) / norm2, dtype="<f8")
            for matrix in (gate, up, down):
                payload = np.asarray(matrix, dtype="<f8").tobytes(order="C")
                digest.update(payload)
                matrix_digests.append(_sha(payload))
        return {
            "full_reconstruction_f64_sha256": digest.hexdigest(),
            "matrix_f64_sha256": matrix_digests,
            "block_indices_i16_sha256": [
                _sha(self.np.asarray(row["indices"], dtype="<i2").tobytes()) for row in decoded
            ],
            "groups_covered_once": True,
        }

    def extract_from_current(self, raw: bytes) -> dict[str, Any]:
        parsed = parse_current_artifact(raw, strata_common=self.strata, frozen_auditor=self.frozen)
        streams = []
        decoded = []
        for row in parsed["blocks"]:
            original = RecordingOriginalDecoder(
                self.frozen.ArithmeticBinaryDecoder(row.payload, 0, row.logical_bits)
            )
            block = self._decode_block(payload=row.payload, logical_bits=row.logical_bits, row=row, arithmetic=original)
            replay, replay_bits = self.frozen.arithmetic_encode_binary(block["selected"], block["base"])
            if replay_bits != row.logical_bits or replay != row.payload:
                raise ValueError(f"baseline canonical replay block {row.ordinal}")
            bits_bytes = self.np.asarray(block["selected"], dtype=self.np.uint8).tobytes()
            levels_bytes = self.np.asarray(block["levels"], dtype=self.np.uint8).tobytes()
            base_bytes = self.np.asarray(block["base"], dtype="<u2").tobytes()
            streams.append({
                "stream_ordinal": row.ordinal,
                "owner_mask": row.owner_mask,
                "weight_charge": 1 << row.logn,
                "symbols": len(bits_bytes),
                "bits": list(bits_bytes),
                "levels": list(levels_bytes),
                "base": [int(value) for value in block["base"].tolist()],
                "bits_bytes": bits_bytes,
                "levels_bytes": levels_bytes,
                "base_bytes": base_bytes,
                "baseline_payload": row.payload,
                "baseline_payload_bytes": len(row.payload),
                "baseline_logical_bits": row.logical_bits,
                "source_digest": _stream_digest(bits_bytes, levels_bytes, base_bytes),
                "profile_q": row.profile_q,
                "decoder_scale": row.decoder_scale,
                "logn": row.logn,
            })
            decoded.append(block)
        if sum(int(row["weight_charge"]) for row in streams) != int(self.strata.WEIGHTS):
            raise ValueError("block weights do not cover parsed shapes")
        metadata = {
            "header": parsed["header"],
            "route": parsed["route"],
            "labels": parsed["labels"],
        }
        reconstruction = self._full_reconstruction_digest(decoded, metadata)
        return {
            "artifact": parsed,
            "immutable_state": pack_immutable_metadata(parsed, self.strata),
            "streams": streams,
            "weights": int(parsed["weights_from_shapes"]),
            "experts": int(self.strata.EXPERTS),
            "reconstruction": reconstruction,
            "baseline_replayed_from_literal_artifact": True,
            "contexts_regenerated_inside_universal_sc_decoder": True,
        }

    def decode_new_container(self, parsed_container: dict[str, Any]) -> dict[str, Any]:
        metadata = unpack_immutable_metadata(parsed_container["immutable_state"], self.strata)
        if int(parsed_container["weights"]) != int(metadata["weights_from_shapes"]):
            raise ValueError("container weights differ from decoded tensor shapes")
        if int(parsed_container["streams"]) != int(self.strata.BLOCKS):
            raise ValueError("container block count")
        decoded = []
        stream_checks = []
        for directory_row, inherited in zip(parsed_container["directory"], metadata["blocks"], strict=True):
            ordinal = int(directory_row["ordinal"])
            if ordinal != int(inherited["ordinal"]):
                raise ValueError("directory/inherited ordinal")
            if int(directory_row["owner_mask"]) != int(inherited["owner_mask"]):
                raise ValueError("directory/inherited owner")
            if int(directory_row["profile_q"]) != int(inherited["profile_q"]):
                raise ValueError("directory/inherited profile")
            if struct.pack("<e", float(directory_row["decoder_scale"])) != inherited["decoder_scale_bits"]:
                raise ValueError("directory/inherited scale")
            base_decoder = self.frozen.ArithmeticBinaryDecoder(
                directory_row["payload"], 0, int(directory_row["logical_bits"])
            )
            arithmetic = UWFAArithmeticDecoder(
                self.common,
                base_decoder,
                parsed_container["candidate"],
                parsed_container["frequencies"],
            )
            block = self._decode_block(
                payload=directory_row["payload"],
                logical_bits=int(directory_row["logical_bits"]),
                row=inherited,
                arithmetic=arithmetic,
            )
            bits_bytes = self.np.asarray(block["selected"], dtype=self.np.uint8).tobytes()
            levels_bytes = self.np.asarray(block["levels"], dtype=self.np.uint8).tobytes()
            base_bytes = self.np.asarray(block["base"], dtype="<u2").tobytes()
            observed_source_digest = _stream_digest(bits_bytes, levels_bytes, base_bytes)
            if observed_source_digest != directory_row["source_digest"]:
                raise ValueError("standalone regenerated context/source digest")
            replay, replay_bits = self.common.encode_unifilar_stream(
                list(bits_bytes),
                list(levels_bytes),
                [int(value) for value in block["base"].tolist()],
                parsed_container["candidate"],
                parsed_container["frequencies"],
            )
            if replay_bits != int(directory_row["logical_bits"]) or replay != directory_row["payload"]:
                raise ValueError("new arithmetic canonical re-encode")
            decoded.append(block)
            stream_checks.append({
                "ordinal": ordinal,
                "selected_bits_sha256": _sha(bits_bytes),
                "base_frequencies_u16_sha256": _sha(base_bytes),
                "source_digest": observed_source_digest,
                "canonical_reencode_matches": True,
            })
        reconstruction = self._full_reconstruction_digest(decoded, metadata)
        if reconstruction["full_reconstruction_f64_sha256"] != parsed_container["reconstruction_sha256"]:
            raise ValueError("full reconstruction binding")
        return {
            "reconstruction": reconstruction,
            "streams": stream_checks,
            "standalone_inputs": ["literal container", "universal frozen codec source", "role/shape semantics in inherited metadata"],
            "used_extracted_arrays_or_input_lock": False,
            "all_payloads_canonically_reencoded": True,
        }
