#!/usr/bin/env python3
"""Fixed STRATA15 evaluation plugin for the universal UWFA-SC v8 core.

No extracted selected-bit, polar-level, or base-frequency file is an input to
this module.  They are regenerated by running the frozen STRATA SC
decoder on the literal inherited metadata and arithmetic payload.  The new
decoder replaces only the arithmetic ``decode(freq1)`` operation.

NumPy, CuPy, the frozen independent STRATA auditor, and the STRATA format
module are injected from an externally authenticated source snapshot.  This
module deliberately performs no repository-relative import. This plugin is
not the universal shape path; the generic semantic adapter owns that claim.
"""

from __future__ import annotations

import hashlib
import math
import struct
from dataclasses import dataclass
from typing import Any, Callable, Sequence


ADAPTER_SCOPE = "EVALUATION_PLUGIN_FIXED_STRATA15_NOT_UNIVERSAL"
IMMUTABLE_MAGIC = b"STUWFA3\x00"
IMMUTABLE_VERSION = 3
IMMUTABLE_HEADER_BYTES = 128
IMMUTABLE_BLOCK_RECORD_BYTES = 40
OWNER_SET_BYTES = 32


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _stream_digest(bits: bytes, levels: bytes, base_u16le: bytes) -> str:
    digest = hashlib.sha256()
    for item in (bits, levels, base_u16le):
        digest.update(struct.pack("<Q", len(item)))
        digest.update(item)
    return digest.hexdigest()


def fixed_owner_set(experts: int, owners: Sequence[int]) -> bytes:
    if type(experts) is not int or not 1 <= experts <= 256:
        raise ValueError("STRATA expert bound")
    values = [int(value) for value in owners]
    if values != sorted(set(values)) or not values or values[0] < 0 or values[-1] >= experts:
        raise ValueError("STRATA owner ordinals")
    result = bytearray(OWNER_SET_BYTES)
    for owner in values:
        result[owner >> 3] |= 1 << (owner & 7)
    return bytes(result)


@dataclass(frozen=True)
class BaselineBlock:
    ordinal: int
    logn: int
    owner_set: bytes
    profile_q: int
    decoder_scale: float
    decoder_scale_bits: bytes
    logical_bits: int
    payload: bytes
    sc_seed_u32: int
    rht_seed_u64: int


def block_contribution_plan(strata_common: Any, labels: Sequence[int]) -> list[dict[str, Any]]:
    """Derive exact per-expert/role charges from the authenticated group map."""
    blocks = strata_common.expected_block_group_ordinals(list(labels))
    experts = int(strata_common.EXPERTS)
    group_values = int(strata_common.GROUP_VALUES)
    groups_per_expert = int(strata_common.GROUPS_PER_EXPERT)
    matrix_weights = int(strata_common.GROUPS_PER_MATRIX) * group_values
    cursors = {(expert, role): 0 for expert in range(experts) for role in ("gate", "up", "down")}
    result = []
    for ordinal, group_ordinals in enumerate(blocks):
        counts: dict[tuple[int, str], int] = {}
        for group in group_ordinals:
            if type(group) is not int or not 0 <= group < experts * groups_per_expert:
                raise ValueError("STRATA group ordinal")
            expert, local = divmod(group, groups_per_expert)
            if local < int(strata_common.GROUPS_PER_MATRIX):
                role = "gate"
            elif local < 2 * int(strata_common.GROUPS_PER_MATRIX):
                role = "up"
            else:
                role = "down"
            counts[(expert, role)] = counts.get((expert, role), 0) + group_values
        contributions = []
        for expert, role in sorted(counts, key=lambda key: (key[0], ("gate", "up", "down").index(key[1]))):
            count = counts[(expert, role)]
            begin = cursors[(expert, role)]
            cursors[(expert, role)] += count
            contributions.append({
                "expert": expert,
                "role": role,
                "source_offset": begin,
                "weight_count": count,
            })
        total = sum(row["weight_count"] for row in contributions)
        if total != 1 << int(strata_common.BLOCK_LOG2[ordinal]):
            raise ValueError("STRATA block contribution conservation")
        owners = sorted({row["expert"] for row in contributions})
        result.append({
            "owner_set": fixed_owner_set(experts, owners),
            "owners": tuple(owners),
            "role": contributions[0]["role"] if len({row["role"] for row in contributions}) == 1 else "mixed",
            "owner_contributions": tuple(contributions),
            "weight_charge": total,
        })
    if any(cursors[(expert, role)] != matrix_weights for expert in range(experts) for role in ("gate", "up", "down")):
        raise ValueError("STRATA per-role contribution coverage")
    return result


class UWFAArithmeticDecoder:
    """Arithmetic-like causal object consumed by ``decode_sc_level``."""

    def __init__(
        self,
        common: Any,
        base_decoder: Any,
        candidate: Any,
        frequencies: Sequence[int],
    ) -> None:
        if len(frequencies) != common.model_frequency_count(candidate):
            raise ValueError("UWFA frequency geometry")
        self.common = common
        self.base_decoder = base_decoder
        self.candidate = candidate
        self.frequencies = frequencies
        self.state = 0
        self.position = 0
        self.level = 0
        self.decoded_bits: list[int] = []
        self.original_frequencies: list[int] = []
        self.uwfa_frequencies: list[int] = []
        self.levels: list[int] = []

    def set_level(self, level_zero_based: int) -> None:
        level = int(level_zero_based)
        if not 0 <= level < self.common.LEVELS:
            raise ValueError("polar level outside universal context")
        self.level = level

    def decode(self, original_freq1: int) -> int:
        within = self.position % self.candidate.reset_length
        if within == 0:
            self.state = 0
        context = self.common.public_context(self.level, int(original_freq1), within)
        uwfa_freq1 = int(self.frequencies[self.state * self.common.CONTEXTS + context])
        bit = int(self.base_decoder.decode(uwfa_freq1))
        if bit not in (0, 1):
            raise ValueError("nonbinary arithmetic decoder result")
        self.decoded_bits.append(bit)
        self.original_frequencies.append(int(original_freq1))
        self.uwfa_frequencies.append(uwfa_freq1)
        self.levels.append(self.level)
        self.state = self.common.transition(self.candidate, self.state, bit, context, within)
        self.position += 1
        return bit


class RecordingOriginalDecoder:
    """Pass-through baseline decoder that records decoder-visible contexts."""

    def __init__(self, decoder: Any) -> None:
        self.decoder = decoder
        self.level = 0
        self.decoded_bits: list[int] = []
        self.original_frequencies: list[int] = []
        self.levels: list[int] = []

    def set_level(self, level_zero_based: int) -> None:
        self.level = int(level_zero_based)

    def decode(self, original_freq1: int) -> int:
        bit = int(self.decoder.decode(int(original_freq1)))
        self.decoded_bits.append(bit)
        self.original_frequencies.append(int(original_freq1))
        self.levels.append(self.level)
        return bit


def parse_current_artifact(
    raw: bytes,
    *,
    strata_common: Any,
    frozen_auditor: Any,
) -> dict[str, Any]:
    """Parse, semantically validate, and byte-slice the held baseline artifact."""
    if len(raw) != int(strata_common.PHYSICAL_BYTES):
        raise ValueError("baseline physical byte count")
    header_end = int(strata_common.HEADER_BYTES)
    route_end = header_end + int(strata_common.ROUTE_BYTES)
    labels_end = route_end + int(strata_common.LABEL_BYTES)
    directory_end = labels_end + int(strata_common.DIRECTORY_BYTES)
    header = raw[:header_end]
    route = raw[header_end:route_end]
    labels_packed = raw[route_end:labels_end]
    directory_raw = raw[labels_end:directory_end]
    strata_common.validate_header(header, route, labels_packed)
    route_rows = strata_common.parse_route(route)
    labels = strata_common.unpack_labels(labels_packed)
    contribution_plan = block_contribution_plan(strata_common, labels)
    if len(route_rows) != int(strata_common.MATRICES):
        raise ValueError("route matrix count")
    shape_weight_sum = 0
    for row in route_rows:
        role = str(row["role"])
        shape = (2048, 768) if role == "down" else (768, 2048)
        shape_weight_sum += shape[0] * shape[1]
    if shape_weight_sum != int(strata_common.WEIGHTS):
        raise ValueError("shape-derived weights disagree with artifact")
    profiles = bytearray()
    cursor = directory_end
    blocks: list[BaselineBlock] = []
    for ordinal in range(int(strata_common.BLOCKS)):
        q, scale, logical_bits = struct.unpack_from(
            "<BeI", directory_raw, ordinal * int(strata_common.DIRECTORY_RECORD_BYTES)
        )
        if not math.isfinite(float(scale)) or float(scale) <= 0.0 or logical_bits <= 0:
            raise ValueError("baseline block directory value")
        payload_bytes = (int(logical_bits) + 7) // 8
        end = cursor + payload_bytes
        if end > len(raw):
            raise ValueError("baseline arithmetic payload outside artifact")
        payload = raw[cursor:end]
        if logical_bits & 7 and payload[-1] & ((1 << (8 - (logical_bits & 7))) - 1):
            raise ValueError("baseline arithmetic terminal padding")
        profiles.append(int(q))
        blocks.append(BaselineBlock(
            ordinal=ordinal,
            logn=int(strata_common.BLOCK_LOG2[ordinal]),
            owner_set=contribution_plan[ordinal]["owner_set"],
            profile_q=int(q),
            decoder_scale=float(scale),
            decoder_scale_bits=directory_raw[ordinal * 7 + 1:ordinal * 7 + 3],
            logical_bits=int(logical_bits),
            payload=payload,
            sc_seed_u32=0,
            rht_seed_u64=0,
        ))
        cursor = end
    if any(raw[cursor:]):
        raise ValueError("nonzero baseline terminal reservoir")
    seeded: list[BaselineBlock] = []
    for row in blocks:
        sc_seed, rht_seed, _digest = strata_common.derive_seeds(
            header, route, labels_packed, bytes(profiles), row.ordinal
        )
        seeded.append(BaselineBlock(
            ordinal=row.ordinal,
            logn=row.logn,
            owner_set=row.owner_set,
            profile_q=row.profile_q,
            decoder_scale=row.decoder_scale,
            decoder_scale_bits=row.decoder_scale_bits,
            logical_bits=row.logical_bits,
            payload=row.payload,
            sc_seed_u32=int(sc_seed),
            rht_seed_u64=int(rht_seed),
        ))
    return {
        "raw_sha256": _sha(raw),
        "raw_bytes": len(raw),
        "weights_from_shapes": shape_weight_sum,
        "header": header,
        "route": route,
        "route_rows": route_rows,
        "labels_packed": labels_packed,
        "labels": labels,
        "profiles": bytes(profiles),
        "blocks": seeded,
        "contribution_plan": contribution_plan,
        "used_payload_end": cursor,
        "zero_tail_bytes": len(raw) - cursor,
    }


def pack_immutable_metadata(parsed: dict[str, Any], strata_common: Any) -> bytes:
    blocks: list[BaselineBlock] = parsed["blocks"]
    body = bytearray()
    body.extend(parsed["header"])
    body.extend(parsed["route"])
    body.extend(parsed["labels_packed"])
    for row in blocks:
        body.extend(struct.pack("<BBH", row.profile_q, row.logn, 0))
        body.extend(row.owner_set)
        body.extend(row.decoder_scale_bits)
        body.extend(b"\x00\x00")
    header = bytearray(IMMUTABLE_HEADER_BYTES)
    total = IMMUTABLE_HEADER_BYTES + len(body)
    struct.pack_into(
        "<8sHHIIIIQ",
        header,
        0,
        IMMUTABLE_MAGIC,
        IMMUTABLE_VERSION,
        IMMUTABLE_HEADER_BYTES,
        int(strata_common.WEIGHTS),
        int(strata_common.EXPERTS),
        int(strata_common.MATRICES),
        int(strata_common.BLOCKS),
        total,
    )
    struct.pack_into("<HH", header, 36, OWNER_SET_BYTES, IMMUTABLE_BLOCK_RECORD_BYTES)
    header[40:72] = hashlib.sha256(body).digest()
    header[72:104] = hashlib.sha256(parsed["header"] + parsed["route"] + parsed["labels_packed"]).digest()
    header[104:128] = hashlib.sha256(bytes(header[:104])).digest()[:24]
    return bytes(header) + bytes(body)


def unpack_immutable_metadata(payload: bytes, strata_common: Any) -> dict[str, Any]:
    if len(payload) < IMMUTABLE_HEADER_BYTES:
        raise ValueError("short inherited metadata")
    magic, version, header_bytes, weights, experts, matrices, blocks, total = struct.unpack_from(
        "<8sHHIIIIQ", payload, 0
    )
    expected = (
        IMMUTABLE_MAGIC,
        IMMUTABLE_VERSION,
        IMMUTABLE_HEADER_BYTES,
        int(strata_common.WEIGHTS),
        int(strata_common.EXPERTS),
        int(strata_common.MATRICES),
        int(strata_common.BLOCKS),
        len(payload),
    )
    if (magic, version, header_bytes, weights, experts, matrices, blocks, total) != expected:
        raise ValueError("inherited metadata constants")
    if struct.unpack_from("<HH", payload, 36) != (OWNER_SET_BYTES, IMMUTABLE_BLOCK_RECORD_BYTES):
        raise ValueError("inherited owner ABI constants")
    if payload[104:128] != hashlib.sha256(payload[:104]).digest()[:24]:
        raise ValueError("inherited metadata header seal")
    body = payload[IMMUTABLE_HEADER_BYTES:]
    if hashlib.sha256(body).digest() != payload[40:72]:
        raise ValueError("inherited metadata body digest")
    cursor = 0
    h_end = cursor + int(strata_common.HEADER_BYTES)
    r_end = h_end + int(strata_common.ROUTE_BYTES)
    l_end = r_end + int(strata_common.LABEL_BYTES)
    header = body[cursor:h_end]
    route = body[h_end:r_end]
    labels_packed = body[r_end:l_end]
    if hashlib.sha256(header + route + labels_packed).digest() != payload[72:104]:
        raise ValueError("inherited semantic metadata digest")
    strata_common.validate_header(header, route, labels_packed)
    labels = strata_common.unpack_labels(labels_packed)
    contribution_plan = block_contribution_plan(strata_common, labels)
    rows = []
    cursor = l_end
    profiles = bytearray()
    for ordinal in range(int(strata_common.BLOCKS)):
        end = cursor + IMMUTABLE_BLOCK_RECORD_BYTES
        if end > len(body):
            raise ValueError("truncated inherited block record")
        q, logn, reserved = struct.unpack_from("<BBH", body, cursor)
        owner_set = body[cursor + 4:cursor + 36]
        scale_bits = body[cursor + 36:cursor + 38]
        if reserved != 0 or body[cursor + 38:end] != b"\x00\x00":
            raise ValueError("inherited block reserved bytes")
        scale = struct.unpack("<e", scale_bits)[0]
        expected_plan = contribution_plan[ordinal]
        if logn != int(strata_common.BLOCK_LOG2[ordinal]) or owner_set != expected_plan["owner_set"]:
            raise ValueError("inherited block geometry")
        if not math.isfinite(float(scale)) or float(scale) <= 0.0:
            raise ValueError("inherited scale")
        profiles.append(q)
        rows.append({
            "ordinal": ordinal,
            "profile_q": int(q),
            "logn": int(logn),
            "owner_set": bytes(owner_set),
            "owner_set_hex": bytes(owner_set).hex(),
            "owner_contributions": expected_plan["owner_contributions"],
            "role": expected_plan["role"],
            "decoder_scale": float(scale),
            "decoder_scale_bits": scale_bits,
        })
        cursor = end
    if cursor != len(body):
        raise ValueError("trailing inherited metadata")
    for row in rows:
        sc_seed, rht_seed, digest = strata_common.derive_seeds(
            header, route, labels_packed, bytes(profiles), row["ordinal"]
        )
        row["sc_seed_u32"] = int(sc_seed)
        row["rht_seed_u64"] = int(rht_seed)
        row["seed_digest_sha256"] = digest
    return {
        "header": header,
        "route": route,
        "route_rows": strata_common.parse_route(route),
        "labels_packed": labels_packed,
        "labels": labels,
        "profiles": bytes(profiles),
        "blocks": rows,
        "contribution_plan": contribution_plan,
        "weights_from_shapes": sum((2048 * 768) for _row in strata_common.parse_route(route)),
    }


class StrataSCAdapter:
    """Authenticated fixed-panel evaluation plugin; not universal geometry."""

    def __init__(self, *, common: Any, semantic_codec: Any, np: Any, frozen_auditor: Any, strata_common: Any, device: str = "cupy") -> None:
        if device not in {"numpy", "cupy"}:
            raise ValueError("RHT device")
        self.common = common
        self.semantic_codec = semantic_codec
        self.np = np
        self.frozen = frozen_auditor
        self.strata = strata_common
        self.device = device

    def _decode_block(
        self,
        *,
        payload: bytes,
        logical_bits: int,
        row: Any,
        arithmetic: Any,
    ) -> dict[str, Any]:
        np = self.np
        n = 1 << int(row.logn if isinstance(row, BaselineBlock) else row["logn"])
        profile_q = int(row.profile_q if isinstance(row, BaselineBlock) else row["profile_q"])
        scale = float(row.decoder_scale if isinstance(row, BaselineBlock) else row["decoder_scale"])
        sc_seed = int(row.sc_seed_u32 if isinstance(row, BaselineBlock) else row["sc_seed_u32"])
        rht_seed = int(row.rht_seed_u64 if isinstance(row, BaselineBlock) else row["rht_seed_u64"])
        profile = self.frozen.profile_parameters(profile_q, 0.25)
        reverse = self.frozen.bit_reverse_indices(n)
        layers = self.frozen.sc_layers(n)
        flags = self.frozen.bec_freeze_flags(n, profile["capacities"], reverse)
        alphabet = 0.25 * np.arange(-31, 33, dtype=np.float64)
        weights = np.exp(-0.5 * (alphabet / float(profile["sigma_reconstruction"])) ** 2)
        previous = np.zeros(n, dtype=np.int16)
        selected_chunks = []
        base_chunks = []
        level_chunks = []
        for level_index, flag in enumerate(flags):
            arithmetic.set_level(level_index)
            level = level_index + 1
            frozen_rng = np.random.default_rng(sc_seed + 1_000_003 * level)
            frozen_external = frozen_rng.integers(0, 2, size=n, dtype=np.uint8)
            prior = self.frozen.leaf_prior_ratios(weights, previous, level)
            x_bit, base_frequencies, selected = self.frozen.decode_sc_level(
                prior, flag, frozen_external, reverse, layers, arithmetic
            )
            previous += (1 << level_index) * x_bit.astype(np.int16)
            selected_chunks.append(selected)
            base_chunks.append(base_frequencies)
            level_chunks.append(np.full(selected.size, level_index, dtype=np.uint8))
        selected_all = np.concatenate(selected_chunks)
        base_all = np.concatenate(base_chunks)
        level_all = np.concatenate(level_chunks)
        transformed = alphabet[previous] * scale
        reconstructed = self.frozen.inverse_signed_rht(transformed, rht_seed, self.device)
        return {
            "selected": selected_all,
            "base": base_all,
            "levels": level_all,
            "indices": previous,
            "reconstructed": reconstructed,
            "logical_bits": int(logical_bits),
            "payload": payload,
        }

    def _full_reconstruction_digest(self, decoded: Sequence[dict[str, Any]], metadata: dict[str, Any]) -> dict[str, Any]:
        np = self.np
        ordinals = self.strata.expected_block_group_ordinals(metadata["labels"])
        post = np.empty((int(self.strata.GROUPS), int(self.strata.GROUP_VALUES)), dtype=np.float64)
        covered: set[int] = set()
        for block, group_ordinals in zip(decoded, ordinals, strict=True):
            if any(int(value) in covered for value in group_ordinals):
                raise ValueError("duplicate decoded group assignment")
            values = np.asarray(block["reconstructed"], dtype=np.float64).reshape(-1, int(self.strata.GROUP_VALUES))
            post[group_ordinals] = values
            covered.update(int(value) for value in group_ordinals)
        if covered != set(range(int(self.strata.GROUPS))):
            raise ValueError("decoded groups do not form exact coverage")
        coefficients = struct.unpack_from("<12f", metadata["header"], 32)
        digest = hashlib.sha256()
        matrix_digests = []
        for expert in range(int(self.strata.EXPERTS)):
            base = expert * int(self.strata.GROUPS_PER_EXPERT)
            gate = np.asarray(post[base:base + 768], dtype="<f8")
            z0 = np.asarray(post[base + 768:base + 1536], dtype=np.float64)
            z1 = np.asarray(post[base + 1536:base + 2304], dtype=np.float64)
            cosine = float(coefficients[2 * expert])
            sine = float(coefficients[2 * expert + 1])
            norm2 = cosine * cosine + sine * sine
            up = np.asarray((cosine * z0 - sine * z1) / norm2, dtype="<f8")
            down = np.asarray((sine * z0 + cosine * z1) / norm2, dtype="<f8")
            for matrix in (gate, up, down):
                payload = np.asarray(matrix, dtype="<f8").tobytes(order="C")
                digest.update(payload)
                matrix_digests.append(_sha(payload))
        return {
            "full_reconstruction_f64_sha256": digest.hexdigest(),
            "matrix_f64_sha256": matrix_digests,
            "block_indices_i16_sha256": [
                _sha(self.np.asarray(row["indices"], dtype="<i2").tobytes()) for row in decoded
            ],
            "groups_covered_once": True,
        }

    def extract_from_current(self, raw: bytes) -> dict[str, Any]:
        parsed = parse_current_artifact(raw, strata_common=self.strata, frozen_auditor=self.frozen)
        streams = []
        decoded = []
        for row, contribution_plan in zip(parsed["blocks"], parsed["contribution_plan"], strict=True):
            original = RecordingOriginalDecoder(
                self.frozen.ArithmeticBinaryDecoder(row.payload, 0, row.logical_bits)
            )
            block = self._decode_block(payload=row.payload, logical_bits=row.logical_bits, row=row, arithmetic=original)
            replay, replay_bits = self.frozen.arithmetic_encode_binary(block["selected"], block["base"])
            if replay_bits != row.logical_bits or replay != row.payload:
                raise ValueError(f"baseline canonical replay block {row.ordinal}")
            bits_bytes = self.np.asarray(block["selected"], dtype=self.np.uint8).tobytes()
            levels_bytes = self.np.asarray(block["levels"], dtype=self.np.uint8).tobytes()
            base_bytes = self.np.asarray(block["base"], dtype="<u2").tobytes()
            streams.append({
                "stream_ordinal": row.ordinal,
                "owner_set_hex": row.owner_set.hex(),
                "owner_contributions": contribution_plan["owner_contributions"],
                "role": contribution_plan["role"],
                "shape_rows": 1,
                "shape_cols": contribution_plan["weight_charge"],
                "weight_charge": contribution_plan["weight_charge"],
                "symbols": len(bits_bytes),
                "bits": list(bits_bytes),
                "levels": list(levels_bytes),
                "base": [int(value) for value in block["base"].tolist()],
                "bits_bytes": bits_bytes,
                "levels_bytes": levels_bytes,
                "base_bytes": base_bytes,
                "baseline_payload": row.payload,
                "baseline_payload_bytes": len(row.payload),
                "baseline_logical_bits": row.logical_bits,
                "source_digest": _stream_digest(bits_bytes, levels_bytes, base_bytes),
                "profile_q": row.profile_q,
                "decoder_scale": row.decoder_scale,
                "logn": row.logn,
            })
            decoded.append(block)
        if sum(int(row["weight_charge"]) for row in streams) != int(self.strata.WEIGHTS):
            raise ValueError("block weights do not cover parsed shapes")
        metadata = {
            "header": parsed["header"],
            "route": parsed["route"],
            "labels": parsed["labels"],
        }
        reconstruction = self._full_reconstruction_digest(decoded, metadata)
        inherited = pack_immutable_metadata(parsed, self.strata)
        shapes = tuple(
            self.semantic_codec.ExpertShape(expert, 2048, 768)
            for expert in range(int(self.strata.EXPERTS))
        )
        semantic_packet = self.semantic_codec.build_semantic_packet(shapes, inherited)
        return {
            "artifact": parsed,
            "semantic_packet": semantic_packet,
            "immutable_state": b"",
            "streams": streams,
            "weights": int(parsed["weights_from_shapes"]),
            "experts": int(self.strata.EXPERTS),
            "expert_shapes": [
                {"expert": expert, "hidden": 2048, "intermediate": 768}
                for expert in range(int(self.strata.EXPERTS))
            ],
            "reconstruction": reconstruction,
            "baseline_replayed_from_literal_artifact": True,
            "contexts_regenerated_inside_universal_sc_decoder": True,
            "adapter_scope": ADAPTER_SCOPE,
        }

    def decode_new_container(self, parsed_container: dict[str, Any]) -> dict[str, Any]:
        metadata = unpack_immutable_metadata(parsed_container["semantics"]["extension"], self.strata)
        if int(parsed_container["weights"]) != int(metadata["weights_from_shapes"]):
            raise ValueError("container weights differ from decoded tensor shapes")
        if int(parsed_container["streams"]) != int(self.strata.BLOCKS):
            raise ValueError("container block count")
        decoded = []
        stream_checks = []
        for directory_row, inherited in zip(parsed_container["directory"], metadata["blocks"], strict=True):
            ordinal = int(directory_row["ordinal"])
            if ordinal != int(inherited["ordinal"]):
                raise ValueError("directory/inherited ordinal")
            if bytes(directory_row["owner_set"]) != bytes(inherited["owner_set"]):
                raise ValueError("directory/inherited owner")
            observed_contributions = tuple(
                {
                    "expert": int(item["expert"]),
                    "role": str(item["role"]),
                    "source_offset": int(item["source_offset"]),
                    "weight_count": int(item["weight_count"]),
                }
                for item in directory_row["owner_contributions"]
            )
            if observed_contributions != tuple(inherited["owner_contributions"]):
                raise ValueError("directory/inherited source contribution map")
            if int(directory_row["profile_q"]) != int(inherited["profile_q"]):
                raise ValueError("directory/inherited profile")
            if struct.pack("<e", float(directory_row["decoder_scale"])) != inherited["decoder_scale_bits"]:
                raise ValueError("directory/inherited scale")
            base_decoder = self.frozen.ArithmeticBinaryDecoder(
                directory_row["payload"], 0, int(directory_row["logical_bits"])
            )
            arithmetic = UWFAArithmeticDecoder(
                self.common,
                base_decoder,
                parsed_container["candidate"],
                parsed_container["frequencies"],
            )
            block = self._decode_block(
                payload=directory_row["payload"],
                logical_bits=int(directory_row["logical_bits"]),
                row=inherited,
                arithmetic=arithmetic,
            )
            bits_bytes = self.np.asarray(block["selected"], dtype=self.np.uint8).tobytes()
            levels_bytes = self.np.asarray(block["levels"], dtype=self.np.uint8).tobytes()
            base_bytes = self.np.asarray(block["base"], dtype="<u2").tobytes()
            observed_source_digest = _stream_digest(bits_bytes, levels_bytes, base_bytes)
            if observed_source_digest != directory_row["source_digest"]:
                raise ValueError("standalone regenerated context/source digest")
            replay, replay_bits = self.common.encode_unifilar_stream(
                list(bits_bytes),
                list(levels_bytes),
                [int(value) for value in block["base"].tolist()],
                parsed_container["candidate"],
                parsed_container["frequencies"],
            )
            if replay_bits != int(directory_row["logical_bits"]) or replay != directory_row["payload"]:
                raise ValueError("new arithmetic canonical re-encode")
            decoded.append(block)
            stream_checks.append({
                "ordinal": ordinal,
                "selected_bits_sha256": _sha(bits_bytes),
                "base_frequencies_u16_sha256": _sha(base_bytes),
                "source_digest": observed_source_digest,
                "canonical_reencode_matches": True,
            })
        reconstruction = self._full_reconstruction_digest(decoded, metadata)
        if reconstruction["full_reconstruction_f64_sha256"] != parsed_container["reconstruction_sha256"]:
            raise ValueError("full reconstruction binding")
        return {
            "reconstruction": reconstruction,
            "streams": stream_checks,
            "standalone_inputs": ["literal container", "universal frozen codec source", "role/shape semantics in inherited metadata"],
            "used_extracted_arrays_or_input_lock": False,
            "all_payloads_canonically_reencoded": True,
        }

    def new_routed_decoder(self) -> Any:
        return _StrataRoutedDecoderSession(self)


class _StrataRoutedDecoderSession:
    """Fresh-expert causal decoder used by descriptor-backed cold proofs."""

    def __init__(self, adapter: StrataSCAdapter) -> None:
        self.adapter = adapter
        self._next_expert = 0
        self._metadata_sha256: str | None = None
        self._full_digest = hashlib.sha256()

    def decode_expert(self, route: dict[str, Any]) -> dict[str, Any]:
        adapter = self.adapter
        expert = int(route["expert_ordinal"])
        if expert != self._next_expert:
            raise ValueError("STRATA routed expert order")
        extension = bytes(route["semantics"]["extension"])
        extension_sha = _sha(extension)
        if self._metadata_sha256 is None:
            self._metadata_sha256 = extension_sha
        elif extension_sha != self._metadata_sha256:
            raise ValueError("STRATA routed immutable metadata changed")
        metadata = unpack_immutable_metadata(extension, adapter.strata)
        block_ordinals = adapter.strata.expected_block_group_ordinals(metadata["labels"])
        groups_per_expert = int(adapter.strata.GROUPS_PER_EXPERT)
        group_values = int(adapter.strata.GROUP_VALUES)
        base_group = expert * groups_per_expert
        post = adapter.np.empty((groups_per_expert, group_values), dtype=adapter.np.float64)
        covered: set[int] = set()
        for directory_row in route["rows"]:
            ordinal = int(directory_row["ordinal"])
            if not 0 <= ordinal < len(metadata["blocks"]):
                raise ValueError("STRATA routed block ordinal")
            inherited = metadata["blocks"][ordinal]
            if ordinal != int(inherited["ordinal"]) or bytes(directory_row["owner_set"]) != bytes(inherited["owner_set"]):
                raise ValueError("STRATA routed directory/inherited identity")
            observed_contributions = tuple(
                {
                    "expert": int(item["expert"]),
                    "role": str(item["role"]),
                    "source_offset": int(item["source_offset"]),
                    "weight_count": int(item["weight_count"]),
                }
                for item in directory_row["owner_contributions"]
            )
            if observed_contributions != tuple(inherited["owner_contributions"]):
                raise ValueError("STRATA routed contribution map")
            if int(directory_row["profile_q"]) != int(inherited["profile_q"]) or struct.pack("<e", float(directory_row["decoder_scale"])) != inherited["decoder_scale_bits"]:
                raise ValueError("STRATA routed profile/scale")
            base_decoder = adapter.frozen.ArithmeticBinaryDecoder(
                directory_row["payload"], 0, int(directory_row["logical_bits"])
            )
            arithmetic = UWFAArithmeticDecoder(
                adapter.common, base_decoder, route["candidate"], route["frequencies"]
            )
            block = adapter._decode_block(
                payload=directory_row["payload"],
                logical_bits=int(directory_row["logical_bits"]),
                row=inherited,
                arithmetic=arithmetic,
            )
            bits_bytes = adapter.np.asarray(block["selected"], dtype=adapter.np.uint8).tobytes()
            levels_bytes = adapter.np.asarray(block["levels"], dtype=adapter.np.uint8).tobytes()
            base_bytes = adapter.np.asarray(block["base"], dtype="<u2").tobytes()
            if _stream_digest(bits_bytes, levels_bytes, base_bytes) != directory_row["source_digest"]:
                raise ValueError("STRATA routed regenerated source digest")
            replay, replay_bits = adapter.common.encode_unifilar_stream(
                list(bits_bytes), list(levels_bytes), [int(value) for value in block["base"].tolist()],
                route["candidate"], route["frequencies"],
            )
            if replay != directory_row["payload"] or replay_bits != int(directory_row["logical_bits"]):
                raise ValueError("STRATA routed canonical re-encode")
            values = adapter.np.asarray(block["reconstructed"], dtype=adapter.np.float64).reshape(-1, group_values)
            for local_index, group_ordinal in enumerate(block_ordinals[ordinal]):
                group_ordinal = int(group_ordinal)
                if base_group <= group_ordinal < base_group + groups_per_expert:
                    target = group_ordinal - base_group
                    if target in covered:
                        raise ValueError("STRATA routed duplicate group")
                    post[target] = values[local_index]
                    covered.add(target)
        if covered != set(range(groups_per_expert)):
            raise ValueError("STRATA routed expert group coverage")
        coefficients = struct.unpack_from("<12f", metadata["header"], 32)
        gate = adapter.np.asarray(post[:768], dtype="<f8")
        z0 = adapter.np.asarray(post[768:1536], dtype=adapter.np.float64)
        z1 = adapter.np.asarray(post[1536:2304], dtype=adapter.np.float64)
        cosine = float(coefficients[2 * expert])
        sine = float(coefficients[2 * expert + 1])
        norm2 = cosine * cosine + sine * sine
        up = adapter.np.asarray((cosine * z0 - sine * z1) / norm2, dtype="<f8")
        down = adapter.np.asarray((sine * z0 + cosine * z1) / norm2, dtype="<f8")
        expert_digest = hashlib.sha256()
        for matrix in (gate, up, down):
            payload = adapter.np.asarray(matrix, dtype="<f8").tobytes(order="C")
            expert_digest.update(payload)
            self._full_digest.update(payload)
        self._next_expert += 1
        return {
            "expert_ordinal": expert,
            "decoded_streams": len(route["rows"]),
            "all_payloads_canonically_reencoded": True,
            "all_three_roles_reconstructed": True,
            "routed_expert_reconstruction_sha256": expert_digest.hexdigest(),
        }

    def finalize(self, *, experts: int, expected_full_reconstruction_sha256: str) -> dict[str, Any]:
        observed = self._full_digest.hexdigest()
        return {
            "experts": experts,
            "full_reconstruction_f64_sha256": observed,
            "matches_container_reconstruction": self._next_expert == experts and observed == expected_full_reconstruction_sha256,
        }
